; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.22"

; Modules
projects[admin][version] = "2.0-beta3"

projects[block_titlelink][version] = "1.3"

projects[ctools][version] = "1.3"

projects[date][version] = "2.6"

projects[devel][version] = "1.3"

projects[ds][version] = "2.2"

projects[entity][version] = "1.1"

projects[field_group][version] = "1.1"

projects[flexslider][version] = "2.0-alpha1"

projects[google_analytics][version] = "1.3"

projects[imagefield_crop][version] = "1.1"

projects[imce][version] = "1.7"

projects[imce_crop][version] = "1.0"

projects[imce_mkdir][version] = "1.0"

projects[imce_wysiwyg][version] = "1.0"

projects[libraries][version] = "2.1"

projects[link][version] = "1.1"

projects[menu_block][version] = "2.3"

projects[metatag][version] = "1.0-beta7"

projects[module_filter][version] = "1.7"

projects[recaptcha][version] = "1.1"

projects[pathauto][version] = "1.2"

projects[print][version] = "1.2"

projects[protected_node][version] = "1.x-dev"

projects[redirect][version] = "1.0-rc1"

projects[search_config][version] = "1.0"

projects[simple_field_formatter][version] = "2.0-beta1"

projects[field_formatter_settings][version] = "1.1"

projects[site_map][version] = "1.0"

projects[scroll_to_top][version] = "2.1"

projects[sharethis][version] = "2.5"

projects[simple_gmap][version] = "1.0"

projects[token][version] = "1.5"

projects[views][version] = "3.7"

projects[views_infinite_scroll][version] = "1.1"

projects[webform][version] = "3.19"

projects[wysiwyg][version] = "2.2"

; Themes
;projects[skeletontheme][version] = "1.2"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[flexslider][download][type] = "git"
libraries[flexslider][download][url] = "https://github.com/woothemes/FlexSlider.git"
libraries[flexslider][directory_name] = "flexslider"
libraries[flexslider][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[ckeditor][download][type] = "get"
libraries[ckeditor][download][url] = "http://download.cksource.com/CKEditor/CKEditor/CKEditor%203.6.6.1/ckeditor_3.6.6.1.zip"
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery.cycle][download][type] = "get"
libraries[jquery.cycle][download][url] = "http://malsup.github.io/jquery.cycle.all.js"
libraries[jquery.cycle][directory_name] = "jquery.cycle"
libraries[jquery.cycle][type] = "library"

