; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.36"

; Modules

projects[addanother][version] = "2.2"

projects[adminimal_admin_menu][version] = "1.5"

projects[betterlogin][version] = "1.3"

projects[block_titlelink][version] = "1.3"

projects[coffee][version] = "2.2"

projects[ctools][version] = "1.7"

projects[date][version] = "2.8"

projects[devel][version] = "1.5"

projects[ds][version] = "2.8"

projects[entity][version] = "1.6"

projects[entityreference][version] = "1.1"

projects[entityreference_view_widget][version] = "2.0-rc6"

projects[inline_entity_form][version] = "1.5"

projects[exclude_node_title][version] = "1.7"

projects[fences][version] = "1.0"

projects[field_collection][version] = "1.0-beta8"

projects[field_group][version] = "1.4"

projects[flexslider][version] = "2.0-alpha3"

projects[google_analytics][version] = "2.1"

projects[html5_tools][version] = "1.2"

projects[imagefield_crop][version] = "1.1"

projects[imce][version] = "1.9"

projects[imce_crop][version] = "1.0"

projects[imce_mkdir][version] = "1.0"

projects[imce_wysiwyg][version] = "1.0"

projects[libraries][version] = "2.2"

projects[link][version] = "1.3"

projects[menu_attributes][version] = "1.0-rc3"

projects[menu_block][version] = "2.5"

projects[metatag][version] = "1.4"

projects[module_filter][version] = "2.0"

projects[mollom][version] = "2.13"

projects[oauth][version] = "3.2"

projects[pathauto][version] = "1.2"

projects[print][version] = "2.0"

projects[protected_node][version] = "1.x-dev"

projects[redirect][version] = "1.0-rc1"

projects[search_config][version] = "1.1"

projects[simple_field_formatter][version] = "2.0-beta3"

projects[site_map][version] = "1.2"

projects[scroll_to_top][version] = "2.1"

projects[sharethis][version] = "2.10"

projects[simple_gmap][version] = "1.2"

projects[superfish][version] = "1.9"

projects[token][version] = "1.6"

projects[twitter_pull][version] = "2.0-rc2"

projects[views][version] = "3.10"

projects[views_infinite_scroll][version] = "1.1"

projects[visitors][version] = "1.9"

projects[webform][version] = "4.7"

projects[weight][version] = "2.4"

projects[workbench][version] = "1.2"

projects[wysiwyg][version] = "2.2"

; Themes
projects[adminimal_theme][version] = "1.21"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[flexslider][download][type] = "git"
libraries[flexslider][download][url] = "https://github.com/woothemes/FlexSlider.git"
libraries[flexslider][directory_name] = "flexslider"
libraries[flexslider][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[ckeditor][download][type] = "get"
libraries[ckeditor][download][url] = "http://download.cksource.com/CKEditor/CKEditor/CKEditor%203.6.6.1/ckeditor_3.6.6.1.zip"
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][type] = "library"


